/***********************************************************************************************************************
 * File Name: system_xc2xx_cm4.c
 *
 * Description: Implementation of SYSTEM and Startup Code
 *
 *
 * (c) Copyright 2024 XIAOHUA SEMICONDUCTOR CO., LTD. All rights reserved.
 *
 * This software is licensed by XHSC PLATFORM SOFTWARE LICENSE AGREEMENT (the "License"). By downloading, installing, or
 * using the Software, you indicate that you accept the terms of the License, and you acknowledge that you have the
 * authority, for yourself or on behalf of your company, to bind your company to these terms. If you do not agree to all
 * of the terms of this License, you should not download or install the Software.
 *
 **********************************************************************************************************************/


/**
 *   @file       system_xc2xx_cm4.c
 *   @version    1.0.0
 *   @brief      system_xc2xx_cm4 Source File with Startup Code
 *   @addtogroup system_driver
 *   @{
 */



#ifdef __cplusplus
extern "C" {
#endif

/***********************************************************************************************************************
 *  INCLUDES
 **********************************************************************************************************************/
#include "system_xc2xx_cm4.h"
#include <stddef.h>

/***********************************************************************************************************************
 *  DEFINES & MACROS
 **********************************************************************************************************************/
#define VTOR_REG  (*(volatile uint32_t *)0xE000ED08UL)

/***********************************************************************************************************************
 *  EXTERN
 **********************************************************************************************************************/
/* External symbols defined by linker */
extern const uint32_t __VECTORTABLE_START;
extern uint32_t __STACK_START;

/* TASKING copytable symbols - generated by linker */
extern const uint32_t __lc_copytable;
extern const uint32_t __lc_copytable_end;

/* Forward declarations */
extern int main(void);
extern void SystemInit(void);

/***********************************************************************************************************************
 *  LOCAL TYPEDEFS
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  LOCAL CONSTANTS
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  LOCAL VARIABLES
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  GLOBAL VARIABLES
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  LOCAL FUNCTION PROTOTYPES
 **********************************************************************************************************************/
static void ClearGenericRegister(void);
static void SetUpVtorRegister(void);
static void SetStack(void);
static void InitData(void);

/***********************************************************************************************************************
 *  LOCAL FUNCTION
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * GLOBAL FUNCTION
 **********************************************************************************************************************/

/**
 * @brief Clear all general-purpose registers
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((noinline))
static void ClearGenericRegister(void)
{
    __asm__ volatile (
        "mov  r0, #0     \n\t"
        "mov  r1, #0     \n\t"
        "mov  r2, #0     \n\t"
        "mov  r3, #0     \n\t"
        "mov  r4, #0     \n\t"
        "mov  r5, #0     \n\t"
        "mov  r6, #0     \n\t"
        "mov  r7, #0     \n\t"
        "mov  r8, #0     \n\t"
        "mov  r9, #0     \n\t"
        "mov  r10, #0    \n\t"
        "mov  r11, #0    \n\t"
        "mov  r12, #0    \n\t"
        "bx   lr         \n\t"
    );
}

/**
 * @brief Set VTOR register to point to vector table
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((noinline))
static void SetUpVtorRegister(void)
{
    VTOR_REG = (uint32_t)&__VECTORTABLE_START;
}

/**
 * @brief Set Main Stack Pointer (MSP)
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((noinline))
static void SetStack(void)
{
    __asm__ volatile (
        "ldr  r0, =__STACK_START  \n\t"
        "msr  msp, r0             \n\t"
        "bx   lr                  \n\t"
    );
}

/**
 * @brief Process copy table - copy data from ROM to RAM and clear BSS
 *            TASKING copytable format: each entry is 3 words (src, dest, len)
 * @param[in]  void
 *
 * @return     void
 */
static void InitData(void)
{
    const uint32_t *copytable = &__lc_copytable;
    const uint32_t *copytable_end = &__lc_copytable_end;

    /* Process each entry in the copy table */
    while (copytable < copytable_end) {
        uint32_t src = copytable[0];    /* Source address in ROM */
        uint32_t dest = copytable[1];   /* Destination address in RAM */
        uint32_t len = copytable[2];    /* Length in bytes */

        copytable += 3;  /* Move to next entry */

        if (len == 0) continue;  /* Skip empty entries */

        if (src == 0) {
            /* BSS clearing - src is 0, fill with zeros */
            uint8_t *p = (uint8_t *)dest;
            while (len--) {
                *p++ = 0;
            }
        } else {
            /* Data initialization - copy from ROM to RAM */
            uint8_t *d = (uint8_t *)dest;
            const uint8_t *s = (const uint8_t *)src;
            while (len--) {
                *d++ = *s++;
            }
        }
    }
}

/**
 * @brief Reset Handler - Entry point for the application
 *            This is the first code executed after reset
 * @param[in]  void
 *
 * @return     void (never returns)
 */
__attribute__((section(".startup")))
void Reset_Handler(void)
{
    /* Disable interrupts */
    __asm__ volatile ("cpsid i" ::: "memory");

    /* Clear all registers */
    ClearGenericRegister();

    /* Set VTOR register */
    SetUpVtorRegister();

    /* Set stack pointer */
    SetStack();

    /* Process copy table (data initialization and BSS clearing) */
    InitData();

    /* System initialization */
    SystemInit();

    /* Enable interrupts and call main */
    __asm__ volatile (
        "cpsie i      \n\t"
        "bl   main     \n\t"
    );

    /* Infinite loop if main returns */
    while(1) {;}
}

/**
 * @brief Default exception handler for unused IRQs
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak))
void Default_Handler(void)
{
    while(1) {;}
}

/**
 * @brief NMI IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void NMI_Handler(void);

/**
 * @brief HardFault IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void HardFault_Handler(void);

/**
 * @brief MemManage IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void MemManage_Handler(void);

/**
 * @brief BusFault IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void BusFault_Handler(void);

/**
 * @brief UsageFault IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void UsageFault_Handler(void);

/**
 * @brief DebugMon IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void DebugMon_Handler(void);

/**
 * @brief PendSV IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void PendSV_Handler(void);

/**
 * @brief SysTick IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void SysTick_Handler(void);

/**
 * @brief SVC IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void SVC_Handler(void);

/**
 * @brief undefined IRQ handler
 * @param[in]  void
 *
 * @return     void
 */
__attribute__((weak, alias("Default_Handler")))
void UnKnown_Handler(void);

/**
 * @brief System Init - called by startup code
 * @param[in] void
 *
 * @return    void
 */
void SystemInit(void)
{
    /* Add system-specific initialization here */
}

#ifdef __cplusplus
}
#endif
